ConversationsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: otherUserId
        KeyType: RANGE
    AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: otherUserId
        AttributeType: S
      - AttributeName: lastModified
        AttributeType: S
    GlobalSecondaryIndexes:
      - IndexName: byUserId
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: lastModified
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    Tags:
      - Key: Environment
        Value: ${self:custom.stage}
      - Key: Name
        Value: conversations-table