DirectMessagesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: conversationId
        KeyType: HASH
      - AttributeName: messageId
        KeyType: RANGE
    AttributeDefinitions:
      - AttributeName: conversationId
        AttributeType: S
      - AttributeName: messageId
        AttributeType: S
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    Tags:
      - Key: Environment
        Value: ${self:custom.stage}
      - Key: Name
        Value: direct-messages-table