RelationshipsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
    AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
      - AttributeName: otherUserId
        AttributeType: S
    GlobalSecondaryIndexes:
      - IndexName: byOtherUser
        KeySchema:
          - AttributeName: otherUserId
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    Tags:
      - Key: Environment
        Value: ${sls:stage}
      - Key: Name
        Value: relationships-table