CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ${sls:stage}-twitter-user-pool
    AutoVerifiedAttributes:
      - email
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireLowercase: false
        RequireNumbers: false
        RequireUppercase: false
        RequireSymbols: false
    UsernameAttributes:
      - email
    Schema:
      - AttributeDataType: String
        Name: name
        Required: false
        Mutable: true
    LambdaConfig:
      PostConfirmation: !GetAtt ConfirmUserSignupLambdaFunction.Arn
